### ISSUE TITLE
Script only processing first item in jackett.xml

### ISSUE THREAD

**Issue by PolliSoft** [max01986/Jackett_RSS_Auto_Downloader#1]
Thanks a lot for creating this script. I can run it without errors, but the script only seems to process the first item in the xml file. Could you test and debug with the attached xml file (
[jackett.log](https://github.com/max01986/Jackett_RSS_Auto_Downloader/files/4898311/jackett.log)
)? 
The xml file has been renamned to .log and washed from api keys.

**Comment by max01986** [comment]
Hi,

Thank you for reporting it.

This is by design since the goal of the script is to automatically download the latest freeleech every XX seconds/minutes.

What I understand you'd like to do is : 

Run the script once and automatically downloads the latest XX or all of the freeleech torrent. This script would not be a loop.

Would it be ok?

**Comment by PolliSoft** [comment]
Thanks a lot for the quick feedback!
I typically set the wait time to 7-8 minutes according to the site's rules, and in this time the chance of several torrent files being added is high.
In my use case, I would still let it run in a loop, and I would expect the script to run through all new items since the last run and download all freeleech torrents from those.
It would also be ok for it to run once in a while and not in a loop. Then I would expect the last item during last run to be saved on disk and be picked up and used as a variable to exit the script once found while looping through the list of items.

**Comment by max01986** [comment]
> Thanks a lot for the quick feedback!
> I typically set the wait time to 7-8 minutes according to the site's rules, and in this time the chance of several torrent files being added is high.
> In my use case, I would still let it run in a loop, and I would expect the script to run through all new items since the last run and download all freeleech torrents from those.
> It would also be ok for it to run once in a while and not in a loop. Then I would expect the last item during last run to be saved on disk and be picked up and used as a variable to exit the script once found while looping through the list of items.

Perfect,

I will see what I can do when I get back from vacation.

**Comment by PolliSoft** [comment]
I had some time to look in to this myself today, and created the script that I was after. Thanks a lot for your work, and feel free to use some of my changes if you want!
https://pastebin.com/7PnBWtHw
