### ISSUE TITLE
Exception while getting downloadvolumefactor value

### ISSUE THREAD

**Issue by PolliSoft** [max01986/Jackett_RSS_Auto_Downloader#2]
Once in a while, I get the following exception when running the script:
```
Exception calling "GetValue" with "1" argument(s): "Index was outside the bounds of the array."
At C:\Utils\Jackett_RSS_Auto_Downloader.ps1:162 char:9
+     if ($item.attr.value.GetValue(6) -eq $DownloadVolumeFactor)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IndexOutOfRangeException
```

My assumption is that the number of attributes for each item in the feed is not always constant, and that the download volume factor should rather be found by traversing through the current item's attributes in some logic as below. I've never scripted in Powershell, and I don't claim, that the below code is even nearly correct, but the logic should be sound enough.

```
	#GET THE DOWNLOADVOLUMEFACTOR
	foreach ($attribute in $item.attr)
	{
		if attribute.name.value.GetValue() -eq "downloadvolumefactor"
		{
			$Factor = attribute.value.GetValue()
		}
	}
```

**Comment by PolliSoft** [comment]
This works:
`                   #GET THE DOWNLOADVOLUMEFACTOR
                    foreach ($attribute in $item.attr)
                    {
                        #Write-PSFMessage -Level Verbose -Message $attribute.value
                        if ($attribute.name -eq "downloadvolumefactor")
                        {
                            $factor = $attribute.value
                        }
                    }`

**Comment by max01986** [comment]
Thank you,

I just added it to my version :)
