### ISSUE TITLE
Added support for many RSS feeds and support for changed DownloadVolumeFactor value after creation

### ISSUE THREAD

**Issue by PolliSoft** [max01986/Jackett_RSS_Auto_Downloader#3]
Please see and use https://pastebin.com/Yag5BeXe if you would like.
In the script, support for one or many RSS feeds is added. 
Also, the parser now goes through all items in all RSS feeds, and only acts on items that has DVF to preferred value that have not already been downloaded before. 
All downloaded torrents are also kept in a log file for them not to be re-downloaded after a restart of the script.

**Comment by max01986** [comment]
Nice work!! 

Thanks
